version: '3.8'

services:
  backend:
    build:
      context: SplunkServer      
    container_name: backend-container
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=splunk
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: SplunkClient     
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: splunk     
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306" #avoiding local conflicts
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
