const express = require('express');
const cors = require('cors');
const mysql = require('mysql2');
const morgan = require('morgan');
const fs = require('fs');
const path = require('path');

// Create a write stream (append mode)
const accessLogStream = fs.createWriteStream(path.join(__dirname, 'access.log'), { flags: 'w' });

// Use morgan to log requests to the file
const app = express();
const port = 3000;
//Interval pointer
let intervalPointer = undefined;
// Parse incoming JSON requests
app.use(express.json());
app.use(cors());
app.use(morgan('combined', { stream: accessLogStream }));
// MySQL Database connection
const db = mysql.createConnection({
  host: process.env.DB_HOST || 'localhost',  
    user: process.env.DB_USER || 'root',
    password: process.env.DB_PASSWORD || '12345678',
    database: process.env.DB_NAME || 'splunk'    
});

// Connect to the MySQL database
db.connect((err) => {
  if (err) {
    console.error('Database connection failed: ' + err.stack);
    return;
  }
  console.log('Connected to the database.');
});

// Define a route to get all data from the table
app.get('/data', (req, res) => {
  // Query to select all data from your table
  db.query('SELECT * FROM test', (err, results) => {
    if (err) {
      console.error('Error retrieving data: ', err);
      return res.status(500).json({ message: 'Error retrieving data' });
    }
    res.json(results);  // Return results as JSON
  });
});

// Define a route to send data to the MySQL table (POST request)
app.post('/data', (req, res) => { 
  const { number } = req.body;  // Get the 'number' from the request body
  let currentNumber = number;
  // Insert data into the table (timestamp is auto-generated by MySQL)
  if(intervalPointer === undefined){
    intervalPointer = setInterval(()=>{
        db.query('INSERT INTO test (number) VALUES (?)', [currentNumber], (err, result) => {
            if (err) {
              console.error('Error inserting data: ', err);              
            }
            currentNumber++;
          });
    },3000);
  }
});
app.post('/stop',(req,res)=>{
    if(intervalPointer)
      {
         clearInterval(intervalPointer);
         intervalPointer = undefined;
      }
})
// Start the server
app.listen(port, () => {
  console.log(`Server is running at http://localhost:${port}`);
});
