apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS splunk;
    USE splunk;
    CREATE TABLE IF NOT EXISTS test (
      id INT AUTO_INCREMENT PRIMARY KEY,
      number INT,
      timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
